CREATE TYPE BeneficiarioList AS TABLE ( NOME VARCHAR(50), CPF VARCHAR(14) );
GO
CREATE PROC FI_SP_IncClienteV2
    @NOME          VARCHAR (50) ,
    @SOBRENOME     VARCHAR (255),
    @NACIONALIDADE VARCHAR (50) ,
    @CEP           VARCHAR (9)  ,
    @ESTADO        VARCHAR (2)  ,
    @CIDADE        VARCHAR (50) ,
    @LOGRADOURO    VARCHAR (500),
    @EMAIL         VARCHAR (2079),
    @TELEFONE      VARCHAR (15) ,
    @CPF           VARCHAR (14),
    @BENEFICIARIOS BeneficiarioList READONLY

AS

DECLARE @ID BIGINT;
BEGIN
	INSERT INTO CLIENTES (NOME, SOBRENOME, NACIONALIDADE, CEP, ESTADO, CIDADE, LOGRADOURO, EMAIL, TELEFONE, CPF) 
	VALUES (@NOME, @SOBRENOME,@NACIONALIDADE,@CEP,@ESTADO,@CIDADE,@LOGRADOURO,@EMAIL,@TELEFONE,@CPF)

	SET @ID = SCOPE_IDENTITY()
    SELECT SCOPE_IDENTITY()

    INSERT INTO BENEFICIARIOS (CPF, NOME, IDCLIENTE)
    SELECT CPF, NOME, @ID FROM @BENEFICIARIOS 
END