CREATE PROC FI_SP_AltCliente
    @NOME          VARCHAR (50) ,
    @SOBRENOME     VARCHAR (255),
    @NACIONALIDADE VARCHAR (50) ,
    @CEP           VARCHAR (9)  ,
    @ESTADO        VARCHAR (2)  ,
    @CIDADE        VARCHAR (50) ,
    @LOGRADOURO    VARCHAR (500),
    @EMAIL         VARCHAR (2079),
    @TELEFONE      VARCHAR (15),
	@CPF		   VARCHAR (14),
	@Id           BIGINT,
	@BENEFICIARIOS BeneficiarioList READONLY
AS
BEGIN
	UPDATE CLIENTES 
	SET 
		NOME = @NOME, 
		SOBRENOME = @SOBRENOME, 
		NACIONALIDADE = @NACIONALIDADE, 
		CEP = @CEP, 
		ESTADO = @ESTADO, 
		CIDADE = @CIDADE, 
		LOGRADOURO = @LOGRADOURO, 
		EMAIL = @EMAIL, 
		TELEFONE = @TELEFONE,
		CPF = @CPF
	WHERE Id = @Id

	MERGE BENEFICIARIOS atual USING @BENEFICIARIOS nova
	ON atual.IDCLIENTE = @Id AND atual.CPF = nova.CPF
	WHEN MATCHED
		THEN 
			UPDATE SET 
				atual.CPF = nova.CPF,
				atual.Nome = nova.Nome
	WHEN NOT MATCHED BY TARGET
		THEN INSERT (NOME, CPF, IDCLIENTE)
			VALUES (nova.Nome, nova.CPF, @Id)
	WHEN NOT MATCHED BY SOURCE
		THEN DELETE;
END