CREATE PROC FI_SP_ConsCliente
	@ID BIGINT
AS
BEGIN
	IF(ISNULL(@ID,0) = 0)
		SELECT NOME, SOBRENOME, NACIONALIDADE, CEP, ESTADO, CIDADE, LOGRADOURO, EMAIL, TELEFONE, ID, CPF FROM CLIENTES WITH(NOLOCK)
	ELSE
		BEGIN
		SELECT * FROM CLIENTES  WITH(NOLOCK) WHERE ID = @ID
		SELECT * FROM BENEFICIARIOS  WITH(NOLOCK) WHERE IDCLIENTE = @ID   
		END
END